<testsuites>
  <testsuite name="timeoutTest" file="/project/test/timeoutTest.php" tests="1" assertions="0" errors="2" warnings="0" failures="0" skipped="0" time="1.014721">
    <testcase name="testTimeoutNotice" class="timeoutTest" classname="timeoutTest" file="/project/test/timeoutTest.php" line="8" assertions="0" time="1.014721">
      <error type="PHPUnit\Framework\RiskyTestError">Risky Test
/project/vendor/phpunit/phpunit/src/TextUI/Command.php:200
/project/vendor/phpunit/phpunit/src/TextUI/Command.php:159
</error>
      <error type="PHPUnit\Framework\RiskyTestError">Risky Test
/project/vendor/phpunit/phpunit/src/TextUI/Command.php:200
/project/vendor/phpunit/phpunit/src/TextUI/Command.php:159
</error>
      <system-out>Custom error log on result test with multiple errors!</system-out>
    </testcase>
  </testsuite>
</testsuites>